//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatis
    {
        public int Id { get; set; }
        public Nullable<int> urunid { get; set; }
        public Nullable<int> personelid { get; set; }
        public Nullable<int> musteriid { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public System.DateTime tarih { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblUrunler TblUrunler { get; set; }
    }
}
